### PR TITLE
Prefer vctrs functions over slower base R equivalents

### PR DESCRIPTION
**Pull request by krlmlr**
for performance.

### CODE REVIEW

**Comment by krlmlr** [comment]
And `split()` by `vec_split()` . Both operations are use a lot, the vctrs version is faster by a factor.

**Comment by krlmlr** [comment]
Gone now.

**Comment by krlmlr** [comment]
Finally green.

Force-pushed, with meaningful individual commits.

**Comment by krlmlr** [comment]
Super-green. Greener than green.

**Comment by lorenzwalthert** [comment]
Great @krlmlr. I was wondering: Do we want to replace all / more of `[` with `vec_slice()`? Because I see more cases, some of them (like in `lag()`) get called on every *nest*, so there might still be room for improvement.

**Comment by krlmlr** [comment]
Good catch! `[` on a vector is harmless, but we do gain a lot with data frames. Expecting another boost with the last commit.

**Review by lorenzwalthert — APPROVED** [review]
Nice. 🥳

**Pull request merged**
