### PR TITLE
Adds me as contributor to `DESCRIPTION`

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by krlmlr** [comment]
Should we add other contributors from https://github.com/r-lib/styler/graphs/contributors too?

**Comment by lorenzwalthert** [comment]
@IndrajeetPatil I was actually just thinking about adding you as a contributor this morning 😊. I think for now @krlmlr I don’t know who else made significant (enough) contributions (or even has interest in being listed), maybe @MichaelChirico, mostly through raising issues. Are you interested @MichaelChirico?

**Comment by IndrajeetPatil** [comment]
@lorenzwalthert and @krlmlr  Apropos this conversation, I am not sure if you had a look at my comment [here](https://github.com/r-lib/styler/pull/972#issuecomment-1215322319).

WDYT?

**Comment by MichaelChirico** [comment]
Up to you who you want to include. I don't think I've contributed much (if any) code, so don't have any expectation of being included.

But if you want to extend authorship to high-volume complainers (🤪) be my guest 😅

**Comment by IndrajeetPatil** [comment]
I am adding myself only as a contributor, btw, and not as an author 😬

**Comment by lorenzwalthert** [comment]
ok @MichaelChirico, feel free to open another PR and add yourself as a contributor.

**Pull request merged**
