### PR TITLE
Replace `purrr::when()` with `if()` equivalents

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
This function will be deprecated in the next (1.0.0) `{purrr}` release (https://github.com/tidyverse/purrr/blob/55c9a8ab8788d878ce9e8e80b867139e46d15395/R/deprec-when.R#L57), and so we should remove its usage to prevent user-facing deprecation messages.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks. I am not sure we should port it since it requires maintenance. Can't we just use `if`, as the docs suggest? Also, when does this require a new release on CRAN to avoid a user facing warning?

**Comment by IndrajeetPatil** [comment]
> Can't we just use `if`, as the docs suggest? 

Done. No longer porting over the function.

> Also, when does this require a new release on CRAN to avoid a user facing warning?

IIRC, `{purrr}` is scheduled for CRAN submission on the 15th of December.

**Comment by lorenzwalthert** [comment]
> IIRC, {purrr} is scheduled for CRAN submission on the 15th of December.

Should we release a new version before that?

**Review by lorenzwalthert — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
> Should we release a new version before that?

Yes, I think that would be a good idea. Maybe at the end of this month? 

Btw, can I upgrade myself from `ctb` to `aut` for the next release? 
I don't know if you have a particular milestone in mind when this should happen.

**Pull request merged**
