### PR TITLE
Separate from potential "Warning message"

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

I recently saw grafik and would thus like to suggest this minimum viable formatting improvement.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks Kathrin. Is the warning you got related to styler? Also, we could maybe even append a line break instead of a space, i.e. setting `fill = TRUE` and leaving the message string untouched. What do you think?

**Comment by katrinleinweber** [comment]
I personally don't like the look of

grafik

but what you suggest is surely better code style ;-)

**Comment by lorenzwalthert** [comment]
Ok ;-). No idea why the CI build fails. Probably unrelated to your changes though...

**Comment by lorenzwalthert** [comment]
Unfortunately I don't have the access rights to re-trigger the build, but I think the problem might have vanished since there were no problems in #391. Can you retrigger the build by an empty ammendment of the last commit (i.e. with `git commit --amend`)? Maybe there is also a GitHub GUI way to do that.

**Comment by lorenzwalthert** [comment]
Thanks @katrinleinweber. Will merge as soon as current master build is fixed. Some issues with `pkgload` being missing, most likely because we now use the `pkgdown` version from CRAN and the package is not in the corresponding `Remotes:` entry.

**Comment by lorenzwalthert** [comment]
Thanks 😊

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
