### PR TITLE
Add `{lintr}` precommit hook and remove existing lints

### LINKED ISSUE #1055: Add {lintr} pre-commit hook
with the config developed [here](https://github.com/r-lib/styler/pull/1020/files). I am not sure how to store this in a `.lintr` file. Any idea @IndrajeetPatil?

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Closes #1055

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
if you don't want to keep pushing and waiting, just run `pre-commit run lintr` locally as explained in the [CI vignette](https://lorenzwalthert.github.io/precommit/articles/ci.html) and the pre-commit [docs](https://pre-commit.com/#pre-commit-run).

**Comment by IndrajeetPatil** [comment]
@lorenzwalthert Any ideas what this error is about?

```r
Error in `precommit::roxygenize_with_cache()`:
! invalid 'expand' argument
Backtrace:
    ▆
 1. └─precommit::roxygenize_with_cache(key = wd, dirs = path_relative_cache)
 2.   └─rlang::abort(conditionMessage(out))
```

**Comment by lorenzwalthert** [comment]
ugh... No, I don't know.

**Comment by IndrajeetPatil** [comment]
I think I figured out what was causing the issue. Let's see if the builds pass now.

**Comment by lorenzwalthert** [comment]
Glad you found the issue. Is that relevant for the CRAN version in any way? Ie could the user get the same an error?

**Review by lorenzwalthert — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
No, no, I had messed up some code while working on the PR, and that's why it was failing. All good now.

**Pull request merged**
