### PR TITLE
Wrap lines longer than option "width".

### PR DESCRIPTION
**Pull request by krivit**
This is WIP. References r-lib/styler#247. Opening the pull request per https://github.com/r-lib/styler/issues/247#issuecomment-383902832.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
I thought a bit about this and I think in principle your approach seems to be a reasonable solution. However, I think in order for the PR to be merged, there are quite a few things I would like to change. Do you want to do that yourself or is it too tedious for you and you are happy if I do it? I am open to both. If you don't want to do it yourself, I'd ask you to close this PR and create a new PR to another (yet to be created) branch. Here's a sketch of I think needs to be done:

* rebasing on master and resolve merge conflicts.
* apply styler to the PR.
* replace base R calls to `apply()` and friends with purrr equivalents.
* replace the `repeat()` and `while()` statements with recursions.
* documenting with roxygen.
* adding unit tests and thinking of exceptions.
* some minor code refactoring (i.e. don't define functions within functions, function re-naming, exposing of the width argument).

**Comment by krivit** [comment]
Thanks for looking into this. If you're willing to do the rest, I'm happy to hand it over.

I don't quite follow what you want me to do, though. Do you want me to create a new branch at `krivit/styler`, make no changes to it at all, and then initiate a PR from that?

**Comment by lorenzwalthert** [comment]
Ok, fine. No, I just meant that you create a PR to `r-lib/styler#line-with`, which I will merge immediately. Then, I will continue to develop from there before I merge the changes into `master`. If I merged this PR, it would take effect to `master` immediately, which I prefre not to happen.

**Comment by lorenzwalthert** [comment]
I just did the work for you @krivit. Welcomed to follow-up on the development and test. Thanks for the initial work.

**Comment by krivit** [comment]
@lorenzwalthert , I see. Thanks!

**Pull request closed without merging**
