### PR TITLE
DO NOT MERGE: Add lint GHA workflow

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
I am not sure we need this. We already have pre-commit to run lintr...

**Comment by IndrajeetPatil** [comment]
I agree. I wasn't actually planning to merge this; this is why I marked it as a draft PR. Just wanted to check currently present lints, and take it from there. Will close it afterwards.

**Comment by IndrajeetPatil** [comment]
Also, good news is that the touchstone update is working. As expected, benchmarking is not run for this PR :)

**Comment by lorenzwalthert** [comment]
Do you want to re-scope this PR into adding lintr support via pre-commit and a `.lintr` file?

**Comment by IndrajeetPatil** [comment]
Why not just the lint GHA? What's the benefit of including it in the precommit action?

**Comment by lorenzwalthert** [comment]
We would include it in pre-commit and then it would run on commit locally and avoid:
* push by GitHub Action and waiting.
* git history convolution.
* consistency with local interactive {lintr} run that depend on `.lintr`.

**Pull request closed without merging**
