### PR TITLE
add emacs reformatter instructions

### LINKED ISSUE #517: styler in Emacs via reformatter
Just an FYI, I've written a small snippet to use styler in Emacs. 

Issue about it in `reformatter.el`
https://github.com/purcell/reformatter.el/issues/11#issuecomment-495459306
`snippet`
https://github.com/Emiller88/doom-emacs-private/blob/6aedee9bb7a5624f1dd63fcd5b6534aad400101a/config.org#reformatter

If you're reading this and you're not a Doom emacs user, `def-package!` is just a very thin wrapper around `use-package`

### PR DESCRIPTION
**Pull request by Emiller88**
Closes #517

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
I believe it would make more sense to link to https://github.com/Emiller88/doom-emacs-private/blob/6aedee9bb7a5624f1dd63fcd5b6534aad400101a/config.org#reformatter than to a comment in the issue don’t you think? Also is this something that can be installed now (ie an Emacs package or something similar) or is the idea to c/p the code?

**Comment by Emiller88** [comment]
I was following what the ALE plugin did, which linked to the dicussion on the ALE issues. 

My hesitation with linking to my personal config, is if I decide to remove/move/etc, then it will break your link.

The package would be `reformatter`, which is a macro to create your own formatters. I'm considering a PR to [emacs-format-all-the-code](https://github.com/lassik/emacs-format-all-the-code), which would be a little less hassle for the end user. But I'll need to go read their package see how they do things differently than reformatter.

Copying and pasting is the usual emacs way. See the [reformatter installation](https://github.com/purcell/reformatter.el#installation) for reference. I could write quite a bit on it if you'd like, but it might bog down your clean README with emacs jargon that most Emacs users would be familar with the boilerplate.

**Comment by lorenzwalthert** [comment]
Ok great you made the PR to 
https://github.com/lassik/emacs-format-all-the-code. So I think it the way of going about installing it from there is standard for emacs users, we won’t need a long description. You are right about the rear, maybe I have to restructure it anyway at some point and

**Comment by lorenzwalthert** [comment]
Sorry closed by mistake -.- 

Ok great you made the PR to 
https://github.com/lassik/emacs-format-all-the-code. So I think if the way of going about installing it from there is standard for emacs users, we won’t need a long description. You are right about the README, maybe I have to restructure it anyway at some point and move some content to vignettes.

**Comment by Emiller88** [comment]
@lorenzwalthert This has been merged https://github.com/lassik/emacs-format-all-the-code/pull/59

I also swapped it to the `emacs-format-all-the-code` link since it's a simple install of that now.

**Comment by lorenzwalthert** [comment]
Thanks @Emiller88.

**Pull request merged**
