### PR TITLE
Check for warnings in examples and tests

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
@lorenzwalthert We can either do this and/or add a [new workflow from lintr](https://github.com/r-lib/lintr/blob/main/.github/workflows/test-package-vigilant.yaml) that runs tests in strict mode.

I prefer doing both, but wanted to first check with you.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
I also prefer both 👍.

**Comment by lorenzwalthert** [comment]
Do we really need a separate workflow or can we incorporate it an existing one?

**Comment by IndrajeetPatil** [comment]
> Do we really need a separate workflow or can we incorporate it an existing one? I try to limit compute time.

Not really. I have consolidated two workflows into one to check for warnings in both examples and tests.

**Review by lorenzwalthert — APPROVED** [review]
Thanks @IndrajeetPatil.

**Pull request merged**
