### PR TITLE
Remove empty lines between roxygen comments and code

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
@lorenzwalthert Creating a draft PR while I figure out the implementation.

As mentioned in #936, I will definitely need some help figuring out a few things since I am not sure if I follow the code logic yet. Will post more concrete questions here as I work through the implementation.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Great start @IndrajeetPatil always good to start with a skeleton and a test. I’d just put `browser()` in your skeleton and run the test. Then, `token`, `token_before` and `token_after` might be helpful. To identify roxygen comment, there might already be some Regex, eg check in the R/roxygen-* files that are used to format Code examples

**Comment by lorenzwalthert** [comment]
Ah and before we forget: at the end, we should also add a transformer drop rule.

**Comment by lorenzwalthert** [comment]
@IndrajeetPatil do you merge manually? I keep getting notifications and I think I don’t want them I until this is ready for review. Converting to draft now.

**Comment by IndrajeetPatil** [comment]
I had opened it as a draft. I am not sure why, but you marked it as ready for review 😅

Screenshot 2022-10-29 at 13 34 35

**Comment by IndrajeetPatil** [comment]
I will actually just close this for now, since there is no value in this PR before including any functionality.

**Pull request closed without merging**
