### PR TITLE
Faster `parse_transform_serialize_r_block()`

### PR DESCRIPTION
**Pull request by krlmlr**
Avoiding repeated `bind_rows()` in transformer.

### CODE REVIEW

**Review by lorenzwalthert — APPROVED** [review]
solid speed improvement. Can't say no to that :D

**Comment by krlmlr** [comment]
I have no idea what's wrong with the macOS tests now.

**Comment by krlmlr** [comment]
https://github.com/r-lib/styler/actions/runs/4722467440/jobs/8377340497?pr=1112#step:2:6693 :

This is how benchmark results would change (along with a 95% confidence interval in relative change) if 0c4187c1bd6acec209292edd94b34496f42b3225 is merged into main:

* &nbsp;&nbsp;:ballot_box_with_check:cache_applying: 204ms -> 205ms [-0.52%, +1.76%]
* &nbsp;&nbsp;:rocket:cache_recording: 941ms -> 859ms [-9.08%, -8.24%]
* &nbsp;&nbsp;:rocket:without_cache: 1.95s -> 1.74s [-11.01%, -10.55%]

**Comment by krlmlr** [comment]
In #1114 now.

**Pull request closed without merging**
