### PR TITLE
Wrap long lines

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Reference: #390.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
[ ] rebasing on master and resolve merge conflicts.
[ ] apply styler to the PR.
[ ] replace base R calls to `apply()` and friends with purrr equivalents.
[ ] replace the `repeat()` and `while()` statements with recursions.
[ ] documenting with roxygen.
[ ] adding unit tests and thinking of exceptions.
[ ] some minor code refactoring (i.e. don't define functions within functions, function re-naming, exposing of the width argument).

**Comment by lorenzwalthert** [comment]
Potential problems with the current implementation are noted in 
https://github.com/r-lib/styler/issues/247#issuecomment-380282032

**Comment by krlmlr** [comment]
I'm seeing:

``` r
styler::style_text("1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1")
#> 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 +
#> 
#>   1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
#>   + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
```

<sup>Created on 2018-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

All lines must end in a `+` .

**Comment by krlmlr** [comment]
Moreover, the following loops indefinitely:

```r
styler::style_text('styler::style_text("1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1")')
```

**Comment by lorenzwalthert** [comment]
Ok, merging this now (not into master, just into the r-lib devel branch). Thanks @krivit.

**Comment by pat-s** [comment]
Has the `line-with` branch ever been tried out in practice? I would be willing to though it would need a rebase with master - and I am afraid to run into merge conflicts :)

**Comment by lorenzwalthert** [comment]
Let's continue this discussion in #496.

**Pull request merged**
