### PR TITLE
Leave comments on line after `{`

### LINKED ISSUE #1004: Comment positions not preserved when preceded by a brace (`{`)
For example, in `{lintr}`, you can include directives in comments that instruct if the line of code in question should not be linted with a certain linter, etc. But `{styler}` changes positions of such comments, which means these directives will no longer work:

``` r
styler::style_text(
  "T_and_F_symbol_linter <- function() { # nolint: object_name.
  }"
)
#> T_and_F_symbol_linter <- function() {
#>   # nolint: object_name.
#> }
```

<sup>Created on 2022-09-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #1004.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Yikes, why isn't the benchmarking working?!

Oh, IINM, YAML is case-sensitive, right? So we need to change this to `- "R/**"`?

https://github.com/r-lib/styler/blob/d8283b0232e13d9d333c4fb6f453fb09580c65e0/.github/workflows/touchstone-receive.yaml#L12

**Comment by lorenzwalthert** [comment]
I would assume YAML is case sensitive and parses `"r/**"  to `"r/**"`. Question is more if GitHub Actions syntax is case sensitive.

**Comment by lorenzwalthert** [comment]
@IndrajeetPatil seems to work now with {touchstone}, committed directly to main.

**Review by IndrajeetPatil — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
