### PR TITLE
No blank lines in function headers

### LINKED ISSUE #549: Redundant line breaks in function header not removed when formatting
After resolving #541, `tryCatch` blocks now terminate in a new line.

```
code <- "tryCatch({
  my_options <- options()
  print('hello!')
},
error = function(e) e)
"
styler::style_text(code)
#> tryCatch(
#>   {
#>    my_options <- options()
#>    print("hello!")
#>  },
#>  error = function(e) e
#> )
```

This seems like one good case from #125, but there are examples in that issue where the original formatting was considered correct.

Similarly, function signatures that used a wrapped style for arguments also end in an empty new line.

```
code <- "function(
    my_indendented_arg, and_another) {
  print('hello')
}"
styler::style_text(code)
#> function(
#>          my_indendented_arg, and_another) {
#>   print("hello")
#> }
```

These seem to be related as cases where there are empty new lines after an opening paren.

Thanks!

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #549.

### CODE REVIEW

**Comment by krlmlr** [comment]
This might be too strict.

## With this PR

``` r
styler::style_text("c(\n  a,\n\n  b\n)")
#> c(
#>   a,
#>   b
#> )
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## CRAN version

``` r
styler::style_text("c(\n  a,\n\n  b\n)")
#> c(
#>   a,
#> 
#>   b
#> )
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment]
This behavior was introduced in #629. I think it’s exactly as intended. When and why would you prefer the blank line not to be removed?

**Comment by krlmlr** [comment]
The empty line allows for better structuring of the code in my case, see https://github.com/krlmlr/dm/commit/155570beda515a67ceb58106207d9ef1a3ae3901. I'm really looking for

Screenshot from 2020-04-12 08-10-40

**Comment by krlmlr** [comment]
Adding an empty comment as a placeholder works but adds noise. Can we be more liberal with empty lines, e.g. only remove if `strict = TRUE`?

**Comment by lorenzwalthert** [comment]
It is only for `strict = FALSE`: 
``` r
styler::style_text(
  "c(
  1, 
  
  2
  )
  ",
  strict = FALSE
)
#> c(
#>   1,
#> 
#>   2
#> )
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But I wonder if there are other ways to accommodate for your use case. Can you specify conditions under which you want to allow blank lines, e.g.

- function calls with more than *k* lines.
- arguments must be named 
- arguments must be multi-line.

etc.?

**Comment by krlmlr** [comment]
Indeed, missed that. I also like how the empty line is kept with `strict = FALSE` at the beginning of function code.

``` r
styler::style_text('
f <- function(a = 1,
              b = 2) {

  here("we should keep", "that empty line above")
}', strict = FALSE)
#> 
#> f <- function(a = 1,
#>               b = 2) {
#> 
#>   here("we should keep", "that empty line above")
#> }
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Maybe if there's a comment, we should keep all empty lines around that comment?

**Comment by lorenzwalthert** [comment]
yeah but empty lines after function header is another topic, let's discuss that in #371. Also, there is no intention to remove this empty line, rather in #371 we may even add one for longer function declarations.

> Can you specify conditions under which you want to allow blank lines, e.g.
> - function calls with more than k lines.
> - arguments must be named
> - arguments must be multi-line.
> - only for functions like ifelse(), switch() and friends.
> ?

Any insights on that from your side? While it is ok to defer to `strict = FALSE`, this also has a lot of other implications one does not want because I think `strict` is overloaded.

**Comment by krlmlr** [comment]
Maybe if there's a comment, we should keep all empty lines around that comment?

**Comment by lorenzwalthert** [comment]
You mean to preserve the blank lines in 
```r
utils::globalVariables(c(
   # pipe
   ".",
  
   # nesting
   "data",
   ...
))
```
for example?

This sounds reasonable.

**Comment by krlmlr** [comment]
I'd rather discuss `strict` elsewhere. I think #549 ultimately was about function headers, this PR also changes formatting of long function calls. Can we disentangle?

If in doubt, user code is correct and should be kept unchanged, also with `strict = TRUE`.

My huge `switch()` in https://github.com/krlmlr/dm/commit/155570beda515a67ceb58106207d9ef1a3ae3901 should be rewritten, let's not bother here.

**Comment by lorenzwalthert** [comment]
> I'd rather discuss strict elsewhere. I think #549 ultimately was about function headers, this PR also changes formatting of long function calls. Can we disentangle?

Well the problem was I forgot to update one test in the other PR and then I rebased after merge but for some reason the commit was still part of this PR so sorry for the convolution. I think function headers are not a concern so much and after resolving #630 we can focus on function calls in #632.

**Pull request merged**
