### PR TITLE
Add tests from #353

### PR DESCRIPTION
**Pull request by krlmlr**
After merging, we may need to resolve conflicts in the `indent-eq-formal` branch. But we can see the current behavior in this PR, and the new behavior from the differences in #353.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Ok, so are these 1:1 the tests from #353? So we can merge this branch now and then adapt #353 until the diff is satisfying?

**Comment by krlmlr** [comment]
Yes, but with test results from the current code (obviously). Merging this into #353 (via master) will most likely lead to conflicts, to avoid this we can use

```sh
git fetch
git checkout indent-eq-formal
git merge origin/master -X ours
git push
```

after merging this PR to get a workable branch for #353.

**Comment by lorenzwalthert** [comment]
Ok, I can do that.

**Comment by lorenzwalthert** [comment]
Done, needed to merge on `upstream/master` not `origin/master` as my origin is usually out of date...

**Pull request merged**
